debug: false
httpport: 80
language: nz_language
grpcport: nz_grpc_port
oauth2:
  type: "github" #Oauth2 登录接入类型，github/gitlab/jihulab/gitee/gitea
  admin: "lirentian0215" #管理员列表，半角逗号隔开
  clientid: "313c39e6e931afbe5fa5" # 在 https://github.com/settings/developers 创建，无需审核 Callback 填 http(s)://域名或IP/oauth2/callback
  clientsecret: "f977ace0528359ff81185d6edf53fee52a5d848d"
  endpoint: "" # 如gitea自建需要设置
site:
  brand: "nz_site_title"
  cookiename: "nezha-dashboard" #浏览器 Cookie 字段名，可不改
  theme: "default"
